export interface Festival {
  slug: string;
  name: string;
  date: string; // ISO YYYY-MM-DD (celebrated day)
  month: number; // 1..12
  deity?: string;
  region: "All-India" | "North" | "South" | "East" | "West";
  category: "Major" | "Vrat" | "Ekadashi" | "Purnima" | "Amavasya" | "Regional";
  description: string;
  significance: string;
}

// Curated dataset for 2026 (approximate observed dates).
export const FESTIVALS_2026: Festival[] = [
  {
    slug: "makar-sankranti",
    name: "Makar Sankranti",
    date: "2026-01-14",
    month: 1,
    deity: "Surya",
    region: "All-India",
    category: "Major",
    description: "Marks the sun's transit into Capricorn and the return of longer days.",
    significance: "Harvest festival, holy dip, kite flying and til-gud offerings.",
  },
  {
    slug: "vasant-panchami",
    name: "Vasant Panchami",
    date: "2026-01-23",
    month: 1,
    deity: "Saraswati",
    region: "All-India",
    category: "Major",
    description: "Celebration of learning, arts and the goddess Saraswati.",
    significance: "Yellow attire, worship of books and instruments, start of spring.",
  },
  {
    slug: "maha-shivratri",
    name: "Maha Shivratri",
    date: "2026-02-15",
    month: 2,
    deity: "Shiva",
    region: "All-India",
    category: "Major",
    description: "The great night of Shiva — night-long vigil, fasting and abhishek.",
    significance: "Rudrabhishek, jagran, chanting of Om Namah Shivaya.",
  },
  {
    slug: "holika-dahan",
    name: "Holika Dahan",
    date: "2026-03-03",
    month: 3,
    deity: "Narasimha",
    region: "All-India",
    category: "Major",
    description: "Bonfire night that recalls the triumph of Prahlad.",
    significance: "Community fire, offerings of grains, victory of good over evil.",
  },
  {
    slug: "holi",
    name: "Holi",
    date: "2026-03-04",
    month: 3,
    deity: "Krishna",
    region: "All-India",
    category: "Major",
    description: "The festival of colours celebrating spring, love and unity.",
    significance: "Playing with colours, sweets, community celebrations.",
  },
  {
    slug: "chaitra-navratri",
    name: "Chaitra Navratri Begins",
    date: "2026-03-19",
    month: 3,
    deity: "Durga",
    region: "All-India",
    category: "Major",
    description: "Nine sacred nights dedicated to the nine forms of Durga.",
    significance: "Fasting, kalash sthapana, path of Durga Saptashati.",
  },
  {
    slug: "rama-navami",
    name: "Rama Navami",
    date: "2026-03-27",
    month: 3,
    deity: "Rama",
    region: "All-India",
    category: "Major",
    description: "Birth of Bhagwan Shri Rama, the seventh avatar of Vishnu.",
    significance: "Rama katha, Ramayana path, temple processions.",
  },
  {
    slug: "hanuman-jayanti",
    name: "Hanuman Jayanti",
    date: "2026-04-02",
    month: 4,
    deity: "Hanuman",
    region: "All-India",
    category: "Major",
    description: "Birthday of Hanumanji, the eternal devotee of Rama.",
    significance: "Sundarkand path, Hanuman Chalisa recitation, temple visits.",
  },
  {
    slug: "akshaya-tritiya",
    name: "Akshaya Tritiya",
    date: "2026-04-20",
    month: 4,
    deity: "Vishnu-Lakshmi",
    region: "All-India",
    category: "Major",
    description: "Auspicious day for new beginnings and charity.",
    significance: "Gold purchase, donations, starting new ventures.",
  },
  {
    slug: "vat-savitri",
    name: "Vat Savitri Vrat",
    date: "2026-06-14",
    month: 6,
    deity: "Savitri-Satyavan",
    region: "All-India",
    category: "Vrat",
    description: "Married women fast for the well-being and longevity of their husband.",
    significance: "Circumambulation of the banyan (vat) tree, katha of Savitri.",
  },
  {
    slug: "jagannath-rath-yatra",
    name: "Jagannath Rath Yatra",
    date: "2026-07-15",
    month: 7,
    deity: "Jagannath",
    region: "East",
    category: "Regional",
    description: "The great chariot festival of Bhagwan Jagannath at Puri.",
    significance: "Rath yatra procession, darshan of Jagannath, Balabhadra and Subhadra.",
  },
  {
    slug: "guru-purnima",
    name: "Guru Purnima",
    date: "2026-07-29",
    month: 7,
    deity: "Guru",
    region: "All-India",
    category: "Purnima",
    description: "Day to honour spiritual teachers and Vyasa Muni.",
    significance: "Guru pujan, dana, satsang.",
  },
  {
    slug: "hariyali-teej",
    name: "Hariyali Teej",
    date: "2026-08-16",
    month: 8,
    deity: "Parvati",
    region: "North",
    category: "Vrat",
    description: "Monsoon festival celebrating Shiva and Parvati's union.",
    significance: "Swings, green attire, women's fasting and folk songs.",
  },
  {
    slug: "raksha-bandhan",
    name: "Raksha Bandhan",
    date: "2026-08-28",
    month: 8,
    region: "All-India",
    category: "Purnima",
    description: "Sacred thread of protection tied by sisters on brothers.",
    significance: "Rakhi tying, sweets, family gathering.",
  },
  {
    slug: "krishna-janmashtami",
    name: "Krishna Janmashtami",
    date: "2026-09-04",
    month: 9,
    deity: "Krishna",
    region: "All-India",
    category: "Major",
    description: "Birth of Bhagwan Shri Krishna at midnight.",
    significance: "Fasting, jagran, dahi handi, temple utsav.",
  },
  {
    slug: "ganesh-chaturthi",
    name: "Ganesh Chaturthi",
    date: "2026-09-14",
    month: 9,
    deity: "Ganesha",
    region: "All-India",
    category: "Major",
    description: "Ten-day festival of Ganeshji — the remover of obstacles.",
    significance: "Sthapana of murti, modak offerings, community pandals.",
  },
  {
    slug: "pitru-paksha-begin",
    name: "Pitru Paksha Begins",
    date: "2026-09-27",
    month: 9,
    region: "All-India",
    category: "Major",
    description: "Fortnight of offerings and remembrance for ancestors.",
    significance: "Tarpan, shraddh, pinda dana.",
  },
  {
    slug: "sharadiya-navratri",
    name: "Sharadiya Navratri Begins",
    date: "2026-10-11",
    month: 10,
    deity: "Durga",
    region: "All-India",
    category: "Major",
    description: "Nine nights honouring the Devi in her many forms.",
    significance: "Kalash sthapana, garba, path of Durga Saptashati.",
  },
  {
    slug: "dussehra",
    name: "Vijayadashami (Dussehra)",
    date: "2026-10-20",
    month: 10,
    deity: "Rama-Durga",
    region: "All-India",
    category: "Major",
    description: "Victory of Rama over Ravana; Devi over Mahishasura.",
    significance: "Ravana dahan, shastra pujan, new beginnings.",
  },
  {
    slug: "karva-chauth",
    name: "Karva Chauth",
    date: "2026-10-30",
    month: 10,
    deity: "Shiva-Parvati",
    region: "North",
    category: "Vrat",
    description: "Married women fast from sunrise till moonrise for their husbands.",
    significance: "Sargi, katha, moon darshan, husband's darshan.",
  },
  {
    slug: "dhanteras",
    name: "Dhanteras",
    date: "2026-11-06",
    month: 11,
    deity: "Dhanvantari-Lakshmi",
    region: "All-India",
    category: "Major",
    description: "First day of Diwali; purchase of gold, silver and utensils.",
    significance: "Dhanvantari puja, health and wealth blessings.",
  },
  {
    slug: "diwali",
    name: "Deepavali (Diwali)",
    date: "2026-11-08",
    month: 11,
    deity: "Lakshmi-Ganesha",
    region: "All-India",
    category: "Major",
    description: "The festival of lights celebrating Rama's return to Ayodhya.",
    significance: "Lakshmi puja, diyas, rangoli, sweets, family reunion.",
  },
  {
    slug: "govardhan-puja",
    name: "Govardhan Puja",
    date: "2026-11-09",
    month: 11,
    deity: "Krishna",
    region: "North",
    category: "Major",
    description: "Worship of Govardhan hill lifted by Krishna.",
    significance: "Annakoot, cow puja, offerings of 56 bhog.",
  },
  {
    slug: "bhai-dooj",
    name: "Bhai Dooj",
    date: "2026-11-10",
    month: 11,
    region: "All-India",
    category: "Major",
    description: "Sisters pray for the long life of their brothers.",
    significance: "Tilak, aarti, sweets, gifts.",
  },
  {
    slug: "chhath-puja",
    name: "Chhath Puja",
    date: "2026-11-14",
    month: 11,
    deity: "Surya-Chhathi Maiya",
    region: "East",
    category: "Regional",
    description: "Four-day worship of the Sun and Chhathi Maiya.",
    significance: "Kharna, sandhya arghya, usha arghya, fasting without water.",
  },
  {
    slug: "geeta-jayanti",
    name: "Geeta Jayanti",
    date: "2026-12-19",
    month: 12,
    deity: "Krishna",
    region: "All-India",
    category: "Major",
    description: "The day the Bhagavad Gita was revealed by Krishna to Arjuna.",
    significance: "Gita path, discourses, chanting of chapters.",
  },
];
