// ============================================================
// Phase 14.7 — robots.txt engine.
// Rules are data, not text: the admin panel stores overrides in
// site_settings ("seo.robots") and this module renders the file.
// ============================================================

import {
  SITE_URL,
  SEARCH_CRAWLERS,
  AI_CRAWLERS_ALLOWED,
  AI_CRAWLERS_BLOCKED,
  NOINDEX_PREFIXES,
  SITEMAP_SHARDS,
} from "./constants";

export interface RobotsGroup {
  userAgents: string[];
  allow?: string[];
  disallow?: string[];
  crawlDelay?: number;
}

export interface RobotsConfig {
  groups: RobotsGroup[];
  sitemaps: string[];
  /** Free-form lines appended verbatim (admin escape hatch). */
  extra?: string[];
  /** Kill switch — blocks everything (staging, takedown). */
  blockAll?: boolean;
}

/** Paths no crawler should ever fetch. */
export const DEFAULT_DISALLOW = [...NOINDEX_PREFIXES.map((p) => `${p}/`), "/*?*utm_", "/*?*fbclid"];

export function defaultRobotsConfig(origin = SITE_URL): RobotsConfig {
  return {
    groups: [
      { userAgents: ["*"], allow: ["/"], disallow: DEFAULT_DISALLOW },
      { userAgents: SEARCH_CRAWLERS, allow: ["/"], disallow: DEFAULT_DISALLOW },
      { userAgents: AI_CRAWLERS_ALLOWED, allow: ["/"], disallow: DEFAULT_DISALLOW },
      { userAgents: AI_CRAWLERS_BLOCKED, disallow: ["/"] },
    ],
    sitemaps: [`${origin}/sitemap.xml`, ...SITEMAP_SHARDS.map((s) => `${origin}/${s}`)],
  };
}

/** Merge an admin override (partial JSON from site_settings) over the defaults. */
export function mergeRobotsConfig(
  base: RobotsConfig,
  override: Partial<RobotsConfig> | null | undefined,
): RobotsConfig {
  if (!override) return base;
  return {
    blockAll: override.blockAll ?? base.blockAll,
    groups: override.groups?.length ? override.groups : base.groups,
    sitemaps: override.sitemaps?.length ? override.sitemaps : base.sitemaps,
    extra: override.extra ?? base.extra,
  };
}

export function renderRobotsTxt(config: RobotsConfig): string {
  if (config.blockAll) {
    return ["User-agent: *", "Disallow: /", ""].join("\n");
  }

  const lines: string[] = ["# robots.txt — generated by the SanatanTools SEO engine"];

  for (const group of config.groups) {
    if (!group.userAgents.length) continue;
    lines.push("");
    for (const ua of group.userAgents) lines.push(`User-agent: ${ua}`);
    for (const a of group.allow ?? []) lines.push(`Allow: ${a}`);
    for (const d of group.disallow ?? []) lines.push(`Disallow: ${d}`);
    if (group.crawlDelay) lines.push(`Crawl-delay: ${group.crawlDelay}`);
  }

  if (config.extra?.length) {
    lines.push("", ...config.extra);
  }

  lines.push("");
  for (const s of config.sitemaps) lines.push(`Sitemap: ${s}`);
  lines.push("");

  return lines.join("\n");
}

/** Convenience: defaults + admin override → file body. */
export function buildRobotsTxt(override?: Partial<RobotsConfig> | null, origin = SITE_URL): string {
  return renderRobotsTxt(mergeRobotsConfig(defaultRobotsConfig(origin), override));
}
