// ============================================================
// Phase 14.6 — Site-wide FAQ registry.
// Single source of truth for /faq, /support and FAQPage schema.
// ============================================================

export interface SiteFaq {
  question: string;
  answer: string;
}

export interface SiteFaqGroup {
  title: string;
  items: SiteFaq[];
}

export const SITE_FAQ_GROUPS: SiteFaqGroup[] = [
  {
    title: "Kundli & reports",
    items: [
      {
        question: "How accurate is the Kundli generated by SanatanTools?",
        answer:
          "Charts are computed from Swiss-ephemeris-grade planetary positions with the Lahiri ayanamsa, your exact birth coordinates and IANA timezone — the same maths a professional astrologer's software uses.",
      },
      {
        question: "What is the difference between the free and premium Kundli report?",
        answer:
          "The free report covers the core 6 pages — charts, planetary positions, basic dasha and a summary. The premium report expands this to 22 pages with Mahadasha timelines, yogas and doshas, remedies, Sade Sati and year-ahead predictions.",
      },
      {
        question: "In which languages can I download my report?",
        answer:
          "Reports are available in English, Hindi and Marathi, with full Devanagari typesetting in the PDF.",
      },
      {
        question: "Do you store my birth details?",
        answer:
          "Only if you are signed in and choose to save a chart to your dashboard. Guest calculations are processed and discarded.",
      },
    ],
  },
  {
    title: "Panchang & horoscopes",
    items: [
      {
        question: "Is the Panchang location-aware?",
        answer:
          "Yes. Sunrise, sunset, tithi transitions, Rahu Kaal and Choghadiya are computed for the exact city you select from our global place search.",
      },
      {
        question: "Are the horoscopes written by humans?",
        answer:
          "No. Every daily, weekly, monthly and yearly horoscope is derived from live planetary transits relative to your Rashi — nothing is hand-written or recycled.",
      },
      {
        question: "Should I use my Moon sign or Sun sign?",
        answer:
          "Vedic astrology uses the Moon sign (Rashi). If you do not know yours, generate a free Kundli and it will be shown on the first page.",
      },
    ],
  },
  {
    title: "Plans, payments & refunds",
    items: [
      {
        question: "Which payment methods do you accept?",
        answer:
          "UPI, net banking, cards and wallets in India through Razorpay, and international cards through our global checkout. Prices are shown in your local currency where supported.",
      },
      {
        question: "Are the premium plans recurring?",
        answer:
          "Yes, premium plans renew monthly and can be cancelled any time from Dashboard → Billing. You keep access until the end of the paid period.",
      },
      {
        question: "Can I get a refund?",
        answer:
          "Refund eligibility is described in our Refund & Cancellation Policy. Reach out from the support page and we will review your request.",
      },
    ],
  },
  {
    title: "Account, privacy & app",
    items: [
      {
        question: "Can I use SanatanTools offline?",
        answer:
          "Yes. Install it from your browser menu — the app works offline for saved content and cached Panchang data.",
      },
      {
        question: "How do I delete my account and data?",
        answer:
          "Write to us from the support page and we will delete your account and all associated charts and reports.",
      },
      {
        question: "Do you sell personal data?",
        answer: "Never. See our Privacy Policy for exactly what we collect and why.",
      },
    ],
  },
];

export function allSiteFaqs(): SiteFaq[] {
  return SITE_FAQ_GROUPS.flatMap((g) => g.items);
}
